---
- :date: 10-Jan-2017
  :jira_id: '2143'
  :description: |-
   Fix "References, names, full synonymy" search 
- :date: 10-Jan-2017
  :jira_id: '2128'
  :description: |-
    Remove requirement to confirm changes of reference for names with synonyms.
- :date: 10-Jan-2017
  :jira_id: '2142'
  :description: |-
    Do not offer "nom. inval., nom. dub." as a nomenclatural status
    for editing a name.
- :date: 05-Jan-2017
  :release: true
- :date: 04-Jan-2017
  :jira_id: '2129'
  :description: |-
    Minor fix during testing to handle empty @name_node_tree_link.
- :date: 04-Jan-2017
  :jira_id: '2118'
  :description: |-
    Allow focus on specific search result record via focus_id param.
- :date: 04-Jan-2017
  :jira_id: '2129'
  :description: |-
    Tree edit typeahead offers accepted names up to next higher major rank.
    Also has checkbox to include "higher" ranks.
- :date: 04-Jan-2017
  :jira_id: '2079'
  :description: |-
    Integrate new tree editing facilities - new Tree tab for instances, 
    choose a workspace, show workspace status.
