---
- :date: 10-Feb-2017
  :jira_id: '2226'
  :description: |-
    Latin now appears fifth on the drop-down list of Reference languages.
- :date: 09-Feb-2017
  :jira_id: '2198'
  :description: |-
    Compress multiple embedded spaces in author name and abbreviation.
- :date: 09-Feb-2017
  :jira_id: '2186'
  :description: |-
    Set colour scheme for staging environment based on setting in configuration
    file.
- :date: 02-Feb-2017
  :release: true
- :date: 30-Jan-2017
  :jira_id: '2195'
  :description: |-
    Move author options in search dropdown and new record menu. 
    Remove brackets.
- :date: 30-Jan-2017
  :jira_id: '2196'
  :description: |-
    Change label of the first Name tab to from "Detail" to "Details".
- :date: 30-Jan-2017
  :jira_id: '2176'
  :description: |-
    Reference search with show-instances set applies limit to the instances too.
- :date: 25-Jan-2017
  :jira_id: '2181'
  :description: |-
    Copy standalone instance no longer restricted to QA role.
- :date: 24-Jan-2017
  :jira_id: '2173'
  :description: |-
    Don't show Delete button for Instance in APC.
- :date: 24-Jan-2017
  :jira_id: '2173'
  :description: |-
    Show informative error message when instance delete fails.
- :date: 19-Jan-2017
  :release: true
- :date: 18-Jan-2017
  :jira_id: '2069'
  :description: |-
    The APC Tree heading for a Name on the details tab is no longer a link to
    display the tree in the Instance Editor.
- :date: 17-Jan-2017
  :jira_id: '2081'
  :description: |-
    Tree classification menu now has links to the Tree Editor.
- :date: 16-Jan-2017
  :jira_id: '1741'
  :description: |-
   Make year mandatory for some reference types.
- :date: 16-Jan-2017
  :jira_id: '2133'
  :description: |-
   Maximum value for a reference year is now evaluated at run time - will 
   not need re-starting in the new year.
- :date: 13-Jan-2017
  :release: true
- :date: 13-Jan-2017
  :jira_id: ''
  :description: |-
   Change dash to slash in URL.  This change is now possible and will match
   other URLs.
- :date: 11-Jan-2017
  :jira_id: '2143'
  :description: |-
   Fine tune "References, names, full synonymy" search to show more instances.
- :date: 11-Jan-2017
  :jira_id: '2141'
  :description: |-
   Added instance searches for "ref-exact" and "parent-ref-exact".
- :date: 10-Jan-2017
  :jira_id: '2143'
  :description: |-
   Fix "References, names, full synonymy" search 
- :date: 10-Jan-2017
  :jira_id: '2128'
  :description: |-
    Remove requirement to confirm changes of reference for names with synonyms.
- :date: 10-Jan-2017
  :jira_id: '2142'
  :description: |-
    Do not offer "nom. inval., nom. dub." as a nomenclatural status
    for editing a name.
- :date: 05-Jan-2017
  :release: true
- :date: 04-Jan-2017
  :jira_id: '2129'
  :description: |-
    Minor fix during testing to handle empty @name_node_tree_link.
- :date: 04-Jan-2017
  :jira_id: '2118'
  :description: |-
    Allow focus on specific search result record via focus_id param.
- :date: 04-Jan-2017
  :jira_id: '2129'
  :description: |-
    Tree edit typeahead offers accepted names up to next higher major rank.
    Also has checkbox to include "higher" ranks.
- :date: 04-Jan-2017
  :jira_id: '2079'
  :description: |-
    Integrate new tree editing facilities - new Tree tab for instances, 
    choose a workspace, show workspace status.
